ARDUINO_DIR = /home/sebastien/travail/arduino-1.8.9
ARDUINO_LIBS = arduino-cc1101-master SPI rflink debug
ARDMK_DIR = /home/sebastien/.arduino_mk

USER_LIB_PATH = /home/sebastien/travail/cpp/seb/arduino/libraries

BOARD_TAG = nano
MCU = atmega328

include $(ARDMK_DIR)/Arduino.mk
